horrible change

diff --git a/.local/bin/del b/.local/bin/del
--- a/.local/bin/del
+++ b/.local/bin/del
@@ -1,85 +1,136 @@
-#!/usr/bin/bash
-. ~/.local/func/define_script_directories_in_variables.sh
-shopt -s extglob
+#!/usr/bin/env dash
+hash -r
 
-# -- Defin current branch directory depending on system
-[ -d /home ] &&
-    branchpwd=$(printf '%s\n' "${PWD}" | cut -d '/' -f '1-3')
-[ -d /data/data/com.termux/files/home ] &&
-    branchpwd=$(printf '%s\n' "${PWD}" | cut -d '/' -f '1-6')
-rip_binary=$(which rip 2>/dev/null && : || printf '%s\n' "no_rip")
 # --
-
-# -- if rip is installed and not running with root delete with rip
-[ -x "${rip_binary}" ] && [ ! "${HOME}" = /root ] &&
-    case "${branchpwd}" in
-
-        # -- in the case of branch pwd is inside users home trash to users graveyard
-        ${HOME})
-            [ ! -d "${HOME}/.local/share/graveyard" ] &&
-                mkdir -p ${HOME}/.local/share/graveyard
-            { for item in "${@}"
-                do
-                    rip --graveyard "${HOME}/.local/share/graveyard" "${item}"
-                done ;
-            }
-            ;;
-        # --
-
-        # -- if in a mnt/ dir trash to users graveyard in mnt dir
-        /mnt/*) 
-            [ ! -d "${branchpwd}/graveyard-${USER}" ] &&
-                mkdir -p ${branchpwd}/graveyard-${USER}
-            { for item in "${@}"
-                do
-                    rip --graveyard "${branchpwd}/graveyard-${USER}" "${item}"
-                done ;
-            }
-            ;;
-        # --
-
-        # -- if branchpwd not in user home or a mnt/ dir trash to users system graveyard
-        !(/mnt))
-            [ ! -d "/tmp/graveyard-${USER}" ] &&
-                mkdir -p /tmp/graveyard-${USER}
-            {
-                for item in "${@}"
-                do
-                    rip --graveyard "/tmp/graveyard-${USER}" "${item}"
-                done
-            }
-            # ${fu_d}/for_files_rip2_to_root.sh "${@}"
-            ;;
-        # --
-
-        # -- use user system graveyard in all other cases
-        *)
-            [ ! -d "/tmp/graveyard-${USER}" ] &&
-                mkdir -p /tmp/graveyard-${USER}
-            {
-                for item in "${@}"
-                do
-                    rip --graveyard "/tmp/graveyard-${USER}" "${item}"
-                done
-            }
-            # ${fu_d}/for_files_rip2_to_root.sh "${@}"
-            ;;
-        # --
-    esac || rip_case_failed=1
-# --
-
-# -- if rip is not installed and home is not root home or if rip case failed use the mvtrash script instead
-[ ! -x "${rip_binary}" ] || [ "${rip_case_failed}" = 1 ] &&
-    [ "${HOME}" = "/home/*" -o "${HOME}" = "/data/data/com.termux/files/home" ] && {
-    . ${fu_d}/del_mvtrash.sh ;
+sh_name=$(basename $0)
+invoking_user=$(logname) # get the user running the script
+invoking_user_home="/home/${invoking_user}" # set var for the runnting user
+{ # find and set rip binary
+    rip_bin=$(type rip 2>/dev/null || printf '%s\n' "no_rip") ;
+    [ ! "${rip_bin}" = "no_rip" ] && rip_bin=$(realpath ${rip_bin##* }) ;
 }
 # --
 
-# -- if ran with root user overwtite the home variable with the branchpwd and run mvtrash script
-[ "${HOME}" = /root ] && {
-    printf "$branchpwd" | grep home && {
-        HOME="$branchpwd" &&
-        . ${fu_d}/del_mvtrash.sh ; 
+# -- get the path for source file
+get_fsrc_base_path () {
+    local item=${1} ; # get full path for source file
+    local full_item=$(cd $(dirname ${item}) && pwd)/$(basename "${item}") ;
+    { # get the base path for source path, depending on system
+        [ -d /home ] && {
+            printf '%s\n' "${full_item}" | cut -d '/' -f '1-3' ;
+        } ;
+        [ -d /data/data/com.termux/files/home ] && {
+            printf '%s\n' "${full_item}" | cut -d '/' -f '1-6' ;
+        } ;
     } ;
+    return 0 ;
 }
+# --
+
+# -- generate the specified directories in sequence
+mkdir_folders_inseq () {
+    local first_dir="${1}" ;
+    local end_dir="${2}/" ;
+    [ "${#first_dir}" -gt "${#end_dir}" ] && {
+        # if paths where provided in the wrong order switch the vars
+        local a="${end_dir}" ; local b="${first_dir}" ;
+        local first_dir="${a}" ; local end_dir="${b}" ;
+    } ;
+    local dir_seqence=$({
+        # generate list of the directories to create
+        until [ "${first_dir}" = "${end_dir}" ]
+        do
+            end_dir="${end_dir%/*}"
+            printf '%s\n' "${end_dir}"
+        done | sort ;
+    }) ;
+    { # create the directories depending on if running as root or not
+        [ "$(printf '%s' "${first_dir}" | grep -c "^${invoking_user_home}")" -ge 1 ] && { 
+            printf '%s\n' "${dir_seqence}" |
+            while IFS= read item ; do mkdir -m 700 ${item} ; done ;
+        } ;
+        [ "$(printf '%s' "${first_dir}" | grep -c "^${invoking_user_home}")" -lt 1 ] && {
+            printf '%s\n' "${dir_seqence}" |
+            while IFS= read item ; do mkdir -m 755 ${item} ; done ;
+        } ;
+    } ;
+    # check if the directory path was sucessfully created
+    [ ! -d "${end_dir}" ] && return 1 ;
+    [ -d "${end_dir}" ] && return 0 ;
+}
+mkdir_folders_inseq_ret () {
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: mkdir_folders_inseq: directory was not created sucsessfully" ;
+        exit 1 ;
+    } ;
+    return 0 ;
+}
+# --
+
+# -- delete files to the specified path
+delete_file () {
+    local rip2b="${rip_bin}" ;
+    local path="${1}" ;
+    local item="${2}" ;
+    [ -x "${rip2b}" ] && [ ! "${HOME}" = /root ] && {
+        # trash with rip if installed and not running as root
+        ${rip2b} --graveyard "${path}" "${item}" ;
+    } || { # all other cases use mv to trash the file
+        mv "${item}" "${path}/${item##*/}$(date +%y-%b-%d-%H-%M-%S-%6N)" ||
+        mv "${item}" "${path}/${item}$(date +%y-%b-%d-%H-%M-%S-%6N)" ;
+    } || return 1 ;
+    return 0 ;
+}
+delete_file_ret () {
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: delete_file: faild to delete file" ;
+        exit 1 ;
+    } ;
+    return 0 ;
+}
+# --
+
+# -- main code to run
+files_list="${@}" ;
+printf '%s\n' ${files_list} | while IFS= read file
+# for each file get the base dir and trash the file to the apropiate trash folder
+do
+    fsrc_base_path="$(get_fsrc_base_path ${file})"
+    case "${fsrc_base_path}" in
+        ${invoking_user_home}) # use graveyard in users home
+        base_dir="${invoking_user_home}/.local"
+        trash_path="${base_dir}/share/graveyard"
+        [ ! -x "${rip_bin}" ] && trash_path="${trash_path}/mvtrash" # if rip is not installed append mv folder
+        [ ! -d "${trash_path}" ] && {
+            mkdir_folders_inseq "${base_dir}" "${trash_path}" ; {
+                ret="${?}" ; mkdir_folders_inseq_ret ;
+            } ;
+        }
+        delete_file "${trash_path}" "${file}" ; { ret="${?}" ; delete_file_ret ; }
+        ;;
+        /mnt/*) # use graveyard in the mounted drive
+        # base_dir = ${fsrc_base_path}
+        trash_path="${fsrc_base_path}/graveyard"
+        [ ! -x "${rip_bin}" ] && trash_path="${trash_path}-${invoking_user}/mvtrash-${invoking_user}"
+        [ ! -d "${trash_path}" ] && {
+            mkdir_folders_inseq "${fsrc_base_path}" "${trash_path}" ; {
+                ret="${?}" ; mkdir_folders_inseq_ret ;
+            } ;
+        }
+        delete_file "${trash_path}" "${file}" ; { ret="${?}" ; delete_file_ret ; }
+        ;;
+        *) # use system graveyard in all other cases
+        base_dir="/tmp"
+        trash_path="/tmp/graveyard"
+        [ ! -x "${rip_bin}" ] && trash_path="${trash_path}-${invoking_user}/mvtrash-${invoking_user}"
+        [ ! -d "${trash_path}" ] && {
+            mkdir_folders_inseq "${base_dir}" "${trash_path}" ; {
+                ret="${?}" ; mkdir_folders_inseq_ret ;
+            } ;
+        }
+        delete_file "${trash_path}" "${file}" ; { ret="${?}" ; delete_file_ret ; }
+        ;;
+    esac
+done
+exit 0 ;
 # --
diff --git a/.local/bin/doasedit b/.local/bin/doasedit
--- a/.local/bin/doasedit
+++ b/.local/bin/doasedit
@@ -1,89 +1,177 @@
-#!/usr/bin/env sh
-. ${HOME}/.local/func/define_script_directories_in_variables.sh
-readlinkfsh=$(which readlinkf_posix.sh)
-
-# -- Be sure /tmp as tmp directory by setting TMPDIR env
-export TMPDIR=/tmp
+#!/usr/bin/env dash
+# --
+cleanup () {
+    rm -rf ${tmp_objects%%:*} ;
+}
+trap "exit" HUP QUIT TERM INT ABRT
+trap "cleanup ; kill -- -$$" EXIT
 # --
 
-# -- Catch arguments. and error if a condition is met
-[ -n "${2}" ] && error_messege='expected_only_one_argument'
-[ -z "${1}" ] && error_messege="no_file_path_provided ${error_messege}"
-[ "$(id -u)" -eq 0 ] && error_messege="cannot_be_run_as_root ${error_messege}"
-[ -d "${1}" ] && error_messege="${1}_is_a_directory ${error_messege}"
+# -- catch arguments
+[ "${#}" -gt 1 ] && error_messege='expected_only_one_argument' ;
+[ -z "${1}" ] && error_messege="no_file_path_provided ${error_messege}" ;
+[ "$(id -u)" -eq 0 ] && error_messege="cannot_be_run_as_root ${error_messege}" ;
+[ -d "${1}" ] && error_messege="${1}_is_a_directory ${error_messege}" ;
 [ -n "${error_messege}" ] && { printf '%s\n' "${error_messege}" |
     while IFS= read -r msg
     do
-        printf '%s\n' "doasedit: ${msg}" >&2 
+        printf '%s\n' "$(basename $0): ${msg}" >&2
     done ;
     exit 1 ;
+};
+# --
+
+# -- get the attributes of the file like name and ext
+get_f_name_attributes () {
+    local file_name="${1##*/}" ;
+    [ "${file_name}" = "${file_name##*.}" ] && # check if file has a extention
+        local file_extension="" || local file_extension="${file_name##*.}" ;
+    printf '%s' "${file_name%.*}:${file_extension}" ; # print the data
+    return 0 ;
 }
 # --
 
-# -- Safe shell options
-set -eu
-# --
-
-# -- get true file path, Get filename, extract file extention for use with temp file
-src="$(doas ${readlinkfsh} "${1}")"
-filename="${src##*/}"
-[ "${filename}" = "${filename##*.}" ] &&
-    file_extension="" || file_extension="${filename##*.}"
-# --
-
-# -- Hooks for recursive removing of a temporary directory
-trap 'rm -rf ${tmp_d}' EXIT HUP QUIT TERM INT ABRT
-# --
-
-# -- Create temp dir, Random suffix for temporary files, Create a temp file for the source file
-tmp_d="${TMPDIR}/$(${bi_d}/rsg -r -L 6 -H 10).tmp" &&
-mkdir -p "${tmp_d}" &&
-[ -d "${tmp_d}" ] && printf '%s\n' "${tmp_d}" || {
-    td_error_messege='cannot create temporary directory' ;
-    printf '%s\n' "${td_error_messege}" ;
-    exit 1 ;
+# -- generate a string of random length and random content of numbers and letters
+generate_random_string () {
+    local min="6" ; # define minimal length
+    local max="12" ; # define max length
+    local char_count=$({ # generate the length of the final string
+        ($(od -An -N4 -tu /dev/urandom)${min+%(${max+$max- }$min+1)${max++$min}}) ;
+    }) ;
+    tr -cd "A-Za-z1-9" < /dev/urandom | head -c ${char_count} ; # generate the string
+    return 0 ;
 }
-suffix=$(${bi_d}/rsg -r -L 6 -H 10)
-[ -z "${file_extension}" ] &&
-    tmp_f="${tmp_d}/${filename}.${suffix}" ||
-    tmp_f="${tmp_d}/${filename%%.*}${suffix}.${file_extension}"
 # --
 
-# -- test File writeability condition, test Other conditions
-[ -w "$src" ] && {
-    w_error_message='editing files in a writable directory is not permitted' ;
-    printf '%s\n' "$filename: ${w_error_message}" ;
-    exit 1 ;
+# -- check what auth tool is configured on the system
+check__auth () {
+    local doas_bin=$(realpath /usr/bin/doas) || { # set doas bin, if not in default path try to find it with type
+        local doas_bin=$(type doas) && local doas_bin=$(realpath ${doas_bin##* }) ;
+    } || { doas_bin="" ; true ; } ;
+    local sudo_bin=$(realpath /usr/bin/sudo) || { # like for doas, do the same for sudo
+        local sudo_bin=$(type sudo) && local sudo_bin=$(realpath ${sudo_bin##* }) ;
+    } || { sudo_bin="" ; true ; } ;
+    [ -x "${sudo_bin}" ] && [ ! -x "${doas_bin}" ] && local auth=${sudo_bin} || true ;
+    [ ! -x "${sudo_bin}" ] && [ -x "${doas_bin}" ] && local auth=${doas_bin} || true ;
+    [ ! -x "${sudo_bin}" ] && [ ! -x "${doas_bin}" ] && return 1 ;
+    printf '%s' "${auth}" ;
+    return 0 ;
 }
-[ ! -r "${src}" ] && doas [ -f "${src}" ] && doas cat "${src}" > "${tmp_f}" 2>/dev/null ||
-[ -r "${src}" ] && cat "${src}" > "${tmp_f}" 2>/dev/null || {
-    printf '%s%s\n' \
-    "cannot transfer the content " \
-    "of the file to temporary one" ;
-    exit 1 ;
+check__auth_ret () {
+    ret="${?}" ;
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: check__auth: setup your authentication, uninstall either doas or sudo" ;
+        exit 1 ;
+    } ;
+    return 0 ;
 }
-
-# -- Create copy of the temporary file, Move the contents of a temporary file to its copy for later comparison
-tmp_cf="${tmp_f}.copy"
-cat "${tmp_f}" > "${tmp_cf}"
 # --
 
-# -- Editing the file by the user using the default editor, if not specified, then vi is used
+
+# --
+mkdir_folders_inseq () {
+    local first_dir="${1}" ;
+    local end_dir="${2}/" ;
+    local dir_seqence=$({
+        until [ "${first_dir}" = "${end_dir}" ]
+        do
+            end_dir="${end_dir%/*}"
+            printf '%s\n' "${end_dir}"
+        done | sort ;
+    }) ;
+    [ ! "${HOME}" = /root ] && {
+        printf '%s\n' "${dir_seqence}" |
+        while IFS= read item ; do mkdir -m 700 ${item} ; done ;
+    } 2>/dev/null ;
+    [ "${HOME}" = /root ] && {
+        printf '%s\n' "${dir_seqence}" |
+        while IFS= read item ; do mkdir -m 755 ${item} ; done ;
+    } 2>/dev/null ;
+    [ -d "${end_dir}" ] && return 0 || return 1
+}
+# --
+
+# --
+get_tmp_array () {
+    [ -w "${src_file}" ] && {
+        return 1 ;
+    } ;
+    local tmp_d="${tmpdir}/$(generate_random_string).tmp.d" ;
+    [ ! -d "${tmp_d}" ] && {
+        mkdir_folders_inseq "${tmpdir}" "${tmp_d}" || return 2 ;
+    } ;
+    local suffix=$(generate_random_string) ;
+    local src_f_atributes=$(get_f_name_attributes "${src_file}") ;
+    [ -z "${src_f_atributes##*.}" ] &&
+        local tmp_f="${tmp_d}/${src_f_atributes%%.*}.${suffix}" ||
+        local tmp_f="${tmp_d}/${src_f_atributes%%.*}.${suffix}.${src_f_atributes##*.}"
+    printf '%s' "${tmp_d}:${tmp_f}" ;
+    return 0 ;
+}
+# --
+
+# --
+move_src_2_tmp () {
+    local tmp_f="${1}" ;
+    { [ ! -r "${src_file}" ] && ${auth} [ -f "${src_file}" ] && ${auth} cat "${src_file}" > "${tmp_f}" ;
+    } 2>/dev/null || {
+    [ -r "${src_file}" ] && cat "${src_file}" > "${tmp_f}" ;
+    } 2>/dev/null || {
+        return 1 ;
+    } ;
+    cat "${tmp_f}" > "${tmp_f}.copy" ;
+}
+# --
+
+# --
+verify_changes () {
+    local tmp_f=${1}
+    cmp -s "${tmp_f}" "${tmp_f}.copy" && return 1 || {
+        local attempt=0 ;
+        until doas cp -f "${tmp_f}" "${src_file}"
+        do
+            local attempt=$((attempt + 1))
+            [ "${attempt}" -ge 3 ] && {
+                return 2
+            }
+        done ;
+        return 0 ;
+    } ;
+}
+# --
+
+# --
+sh_name=$(basename $0)
+auth=$(check__auth) ; check__auth_ret
+src_file="$(doas realpath "${1}")"
+tmpdir="${HOME}/tmp"
+tmp_objects="$(get_tmp_array)" ; {
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: get_tmp_array: editing file in writebal dir is not premitted" ; exit 1 ;
+    } ;
+    [ "${ret}" = 2 ] && {
+        printf '%s\n' "${sh_name}: get_tmp_array: faild to make temp directory" ; exit 1 ;
+    } ;
+}
+    tmp_d="$(printf '%s' "${tmp_objects}" | cut -d':' -f'1')"
+    tmp_f="$(printf '%s' "${tmp_objects}" | cut -d':' -f'2')"
+move_src_2_tmp "${tmp_f}" ; {
+    ret="${?}" ;
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: move_src_2_tmp: failed to move ${src_file} to ${tmp_f}" ; exit 1 ;
+    } ;
+}
 ${EDITOR:-vi} "${tmp_f}"
-# --
-
-# -- Compare the temporary file and the temporary copy
-cmp -s "${tmp_f}" "${tmp_cf}" && printf "%s\n" "doasedit: ${filename} unchanged" && exit 0 || {
-    attempt=0 ;
-    until doas cp -f "${tmp_f}" "${src}"
-    do
-        attempt=$((attempt + 1))
-        [ "${attempt}" -ge 3 ] && {
-            c_error_messege='cannot accept changes' ;
-            printf '%s\n' "doasedit: ${c_error_messege}" ;
-        }
-    done ;
-    printf "%s\n" "doasedit: ${filename} changes are accepted" ;
-    exit 0
+verify_changes "${tmp_f}" ; {
+    ret="${?}" ;
+    [ "${ret}" = 0 ] && {
+        printf '%s\n' "${sh_name}: verify_changes: changes accepted to ${src_file}" ; exit 0 ;
+    } ;
+    [ "${ret}" = 1 ] && {
+        printf '%s\n' "${sh_name}: verify_changes: ${src_file} left unchanged" ; exit 1 ;
+    } ;
+    [ "${ret}" = 2 ] && {
+        printf '%s\n' "${sh_name}: verify_changes: attempted force copying ${tmp_f} to ${src_file} with failure" ; exit 1 ;
+    } ;
 }
 # --
